# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6tlTNQlH7mhWxvhxztZ7orYFEmbIVk5
"""

import pandas as pd
!pip install geopandas
import geopandas as gpd

# creamos la variable poblacion en la que  guardamos el datasef de la proyeccion de poblacion
poblacion = pd.read_csv("/content/archivos/poblacion__proyeccion_201.csv",  encoding=" latin1")

# creamos la variable wifi en la que guardamos el datasef de wifi
wifi = gpd.read_file("/content/archivos/wifi_gratis.gpkg")
wifi.head()

!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

import pandas as pd # Librería para el procesamiento de datos
import numpy as np # Librería para análisis vectorial
import matplotlib.pyplot as plt # Librería básica de visualización
import pandas_profiling
from pandas_profiling import ProfileReport

# creamos la variable comuna_barrio que almacena el datasef con los datos de cada barrio por comuna
comuna_barrio = pd.read_csv("/content/archivos/comunas_barrios_medellin.csv")

# aqui unimos los datasef
import pandas as pd

# Normalizar nombres
poblacion['nombre'] = poblacion['nombre'].str.upper().str.strip()
comuna_barrio['Barrio'] = comuna_barrio['Barrio'].str.upper().str.strip()
wifi['barrio'] = wifi['barrio'].str.upper().str.strip()

# Renombrar columnas para facilitar merge
poblacion = poblacion.rename(columns={'nombre': 'Barrio', 'total_2025': 'Poblacion'})
wifi_por_barrio = wifi.groupby('barrio').size().reset_index(name='Puntos_WiFi')
wifi_por_barrio = wifi_por_barrio.rename(columns={'barrio': 'Barrio'})

# Merge: comuna_barrio + poblacion
df = pd.merge(comuna_barrio, poblacion[['Barrio', 'Poblacion']], on='Barrio', how='left')

# Merge: + puntos WiFi
df = pd.merge(df, wifi_por_barrio, on='Barrio', how='left')
df['Puntos_WiFi'] = df['Puntos_WiFi'].fillna(0)

# Calcular métricas
df['WiFi_por_1000_hab'] = df['Puntos_WiFi'] / df['Poblacion'] * 1000
df['Subatendida'] = df['WiFi_por_1000_hab'] < df['WiFi_por_1000_hab'].quantile(0.25)

# Resultado final
print(df.head())

# guardamos el datasef
df.to_csv("cobertura_wifi_medellin.csv", index=False)
# descargamos el nuevo datasef
from google.colab import files
files.download("cobertura_wifi_medellin.csv")

# analisis que se realizo en clase usando pandas profile
analisis_enlazado = pd.read_csv("/content/archivos/cobertura_wifi_medellin (1).csv")

reporte = ProfileReport(analisis_enlazado, title='Perfil de datos poblacion')

reporte.to_notebook_iframe()